name: chatbot_app
description: A Flutter chatbot app with Firebase and Gemini API
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  google_sign_in: ^6.2.1
  flutter_riverpod: ^2.4.9
  http: ^1.2.0
  intl: ^0.18.1
  loading_animation_widget: ^1.2.0+4
  uuid: ^4.2.2
  flutter_spinkit: ^5.2.1
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1  # Added for app icon customization

flutter:
  uses-material-design: true

  assets:
    - assets/images/talko_logo.png

flutter_native_splash:
  color: "#ffffff"              # Background color of splash screen
  image: assets/images/talko_logo.png  # Your custom logo
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/talko_logo.png"
